set=set()
n1=int(input("Enter first number: "))
set.add(n1)
n2=int(input("Enter second number: "))
set.add(n2)
n3=int(input("Enter third number: "))
set.add(n3)
n4=int(input("Enter fourth number: "))
set.add(n4)
n5=int(input("Enter 5th number: "))
set.add(n5)
n6=int(input("Enter 6th number: "))
set.add(n6)
n7=int(input("Enter 7th number: "))
set.add(n7)
n8=int(input("Enter 8th number: "))
set.add(n8)

print(set)